ALTER TABLE profiles ADD COLUMN IF NOT EXISTS prayer TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS marriage_timeline TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS children_wish TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS relocation TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS family_view TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS temperament TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS niyyah TEXT;
